name: flutter_application_7
description: "A new Flutter project."

publish_to: "none" # Prevents the package from being published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Specify the Dart SDK version range

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14 # Added path_provider for file system access

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Add linter for Flutter best practices

flutter:
  uses-material-design: true

  # Specify your assets here
  assets:
    - assets/images/
